### ISSUE TITLE
remove "review this module" from /account page for students quizzes

### ISSUE THREAD

**Issue by miler350** [The-Wildfyre-Group/hip-hop-health#30]
![screen shot 2016-08-31 at 9 29 24 am](https://cloud.githubusercontent.com/assets/3248267/18130573/80af2bcc-6f5d-11e6-88b3-8cd24b72c267.png)

**Comment by khadijah-coakley** [comment]
Are setting it up like this? The aren't really "quizzes" per se and they are on the red cal website mostly so is this view/section even relevant anymore?

**Comment by miler350** [comment]
i just hooked up the design

**Comment by miler350** [comment]
set it up how it makes sense when u finish design. can prob delete that section i think
