### ISSUE TITLE
All Pages to be Designed

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/hip-hop-health#39]
**These are clear:**
/dashboard/wizard
/ambassador/signup
/schools/index
/schools/edit

**/dashboard for Ambassadors** -- What db values / calcs do we have to populate this page? What is it supposed to be capturing per the requirements? General information or specific data?  Is it already present on the page or needs to be added?

Is this a complete list...?

**Comment by miler350** [comment]
/ homepage
instructors/signup
ambassador/signup
/account (for student, instructor, ambassador)
